---
# Application para gerenciar os exemplos do seu reposit√≥rio local
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meus-exemplos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ritamoura1980/crossplane.git
    targetRevision: main
    path: examples
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
# Application para gerenciar as configs do Crossplane
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minhas-configs-crossplane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ritamoura1980/crossplane.git
    targetRevision: main
    path: crossplane-configs
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
